### ISSUE TITLE
Isolate dependency injection to a single Spring Bean by making these private final

### ISSUE THREAD

**Issue by sergejsvisockis** [joejoe2/spring-chat#9]
All Spring bean injections should be `private` and `final` having a scope of use solely within that bean. Otherwise, it violates SRP and becomes quite coupled.

That's totally fine to inject one bean more than twice into other beans.

Continuation of https://github.com/joejoe2/spring-chat/issues/8

**Comment by sergejsvisockis** [comment]
P.S. But IMO chat blockage functionality has had higher priority :)

**Comment by joejoe2** [comment]
added some missing private in controller package

**Comment by sergejsvisockis** [comment]
Looks good!
